/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardDashboardIndexImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardUserIndexImport } from './routes/_dashboard/dashboard/user/index'
import { Route as DashboardDashboardAdminIndexImport } from './routes/_dashboard/dashboard/admin/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardIndexRoute = DashboardDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashboardUserIndexRoute =
  DashboardDashboardUserIndexImport.update({
    id: '/dashboard/user/',
    path: '/dashboard/user/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardDashboardAdminIndexRoute =
  DashboardDashboardAdminIndexImport.update({
    id: '/dashboard/admin/',
    path: '/dashboard/admin/',
    getParentRoute: () => DashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/dashboard/admin/': {
      id: '/_dashboard/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardDashboardAdminIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/dashboard/user/': {
      id: '/_dashboard/dashboard/user/'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardDashboardUserIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardAdminIndexRoute: typeof DashboardDashboardAdminIndexRoute
  DashboardDashboardUserIndexRoute: typeof DashboardDashboardUserIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardAdminIndexRoute: DashboardDashboardAdminIndexRoute,
  DashboardDashboardUserIndexRoute: DashboardDashboardUserIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/admin': typeof DashboardDashboardAdminIndexRoute
  '/dashboard/user': typeof DashboardDashboardUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/admin': typeof DashboardDashboardAdminIndexRoute
  '/dashboard/user': typeof DashboardDashboardUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/admin/': typeof DashboardDashboardAdminIndexRoute
  '/_dashboard/dashboard/user/': typeof DashboardDashboardUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/admin/'
    | '/_dashboard/dashboard/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboard",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/dashboard/",
        "/_dashboard/dashboard/admin/",
        "/_dashboard/dashboard/user/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_dashboard/dashboard/": {
      "filePath": "_dashboard/dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/admin/": {
      "filePath": "_dashboard/dashboard/admin/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/user/": {
      "filePath": "_dashboard/dashboard/user/index.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
